name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Terraform CI/CD
    runs-on: ubuntu-latest
    permissions:
      id-token: write          # Permission for workload identify
      contents: read           # Permission for workload identify
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate gcloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      
      # - name: Authenticate gcloud
      #   uses: google-github-actions/auth@v0
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
          terraform_wrapper: false  # due to https://github.com/gruntwork-io/terragrunt/issues/1202

      - name: Setup Terragrunt
        run: |
          curl -LJO https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.2/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Terragrunt Plan
        run: |
          cd environments
          terragrunt run-all plan --terragrunt-non-interactive

      # - name: Terragrunt Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: |
      #     cd environments
      #     terragrunt run-all apply --auto-approve --terragrunt-non-interactive

      # - name: Terragrunt Destroy
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        # run: |
        #   cd environments
        #   terragrunt run-all destroy --auto-approve --terragrunt-non-interactive
